spring:
  datasource:
    url: jdbc:mysql://localhost:3306/realworld?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

config:
  jwt:
    secretKey: realworld
    expiration: 10000000
